/-
Copyright (c) 2026 Scott Armstrong, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Amélie Loher
-/
module

public import LiebThirring.Kinetic.ContractionTensor

/-! # Operators acting on two finite-spin L² factors

This module lifts a bounded operator pointwise through a finite-spin `L²` factor. It uses
that lift to construct the two tensor insertions and proves that their projection products
commute and equal the projection generated by double insertion.
-/

public section

open MeasureTheory WithLp
open scoped InnerProduct

namespace LiebThirring

variable {ι α E F : Type*} [Fintype ι] [MeasurableSpace α]
  [NormedAddCommGroup E] [InnerProductSpace ℂ E]
  [NormedAddCommGroup F] [InnerProductSpace ℂ F]
  {μ : Measure α}

@[expose] noncomputable def piLpMap (T : E →L[ℂ] F) :
    PiLp 2 (fun _ : ι => E) →L[ℂ] PiLp 2 (fun _ : ι => F) :=
  ({ toFun := fun u => toLp 2 (fun s => T (u s))
     map_add' := fun u v => by ext s; change T (u s + v s) = T (u s) + T (v s); rw [map_add]
     map_smul' := fun c u => by ext s; change T (c • u s) = c • T (u s); rw [map_smul] } :
      PiLp 2 (fun _ : ι => E) →ₗ[ℂ] PiLp 2 (fun _ : ι => F)).mkContinuous ‖T‖ (fun u => by
        apply (sq_le_sq₀ (norm_nonneg _) (mul_nonneg (norm_nonneg T) (norm_nonneg u))).mp
        rw [PiLp.norm_sq_eq_of_L2, mul_pow, PiLp.norm_sq_eq_of_L2]
        calc
          ∑ s : ι, ‖T (u s)‖ ^ 2 ≤ ∑ s : ι, (‖T‖ * ‖u s‖) ^ 2 :=
            Finset.sum_le_sum fun s _ =>
              (sq_le_sq₀ (norm_nonneg _) (mul_nonneg (norm_nonneg T) (norm_nonneg _))).mpr
                (T.le_opNorm _)
          _ = ‖T‖ ^ 2 * ∑ s : ι, ‖u s‖ ^ 2 := by
            rw [Finset.mul_sum]
            apply Finset.sum_congr rfl
            intro s _
            ring
          _ = _ := rfl
        )

@[expose] noncomputable def tensorTargetLift (T : E →L[ℂ] F) :
    Lp (PiLp 2 (fun _ : ι => E)) 2 μ →L[ℂ]
      Lp (PiLp 2 (fun _ : ι => F)) 2 μ :=
  (piLpMap (ι := ι) T).compLpL 2 μ

theorem tensorTargetLift_apply_ae (T : E →L[ℂ] F)
    (u : Lp (PiLp 2 (fun _ : ι => E)) 2 μ) :
    ∀ᵐ x ∂μ, ∀ s : ι, tensorTargetLift T u x s = T (u x s) := by
  filter_upwards [(piLpMap (ι := ι) T).coeFn_compLp' u] with x hx
  intro s
  change ((piLpMap (ι := ι) T).compLp u) x s = T (u x s)
  exact congrArg (fun z : PiLp 2 (fun _ : ι => F) => z s) hx

theorem tensorTargetLift_comp_tensorInsertion
    (T : E →L[ℂ] F) (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    tensorTargetLift (ι := ι) (μ := μ) T ∘L tensorInsertion (H := E) f =
      tensorInsertion (H := F) f ∘L T := by
  apply ContinuousLinearMap.ext
  intro v
  apply Lp.ext
  filter_upwards [tensorTargetLift_apply_ae (ι := ι) T (tensorInsertion (H := E) f v),
    tensorInsertion_apply_ae (H := E) f v,
    tensorInsertion_apply_ae (H := F) f (T v)] with x hl hi hr
  apply PiLp.ext
  intro s
  change tensorTargetLift (ι := ι) (μ := μ) T (tensorInsertion (H := E) f v) x s =
    tensorInsertion (H := F) f (T v) x s
  rw [hl s, hi s, hr s, map_smul]

section Complete

variable [CompleteSpace E] [CompleteSpace F]

theorem piLpMap_adjoint (T : E →L[ℂ] F) :
    (piLpMap (ι := ι) T).adjoint = piLpMap (ι := ι) T.adjoint := by
  apply ContinuousLinearMap.ext
  intro u
  apply ext_inner_right ℂ
  intro v
  rw [ContinuousLinearMap.adjoint_inner_left]
  simp only [PiLp.inner_apply]
  apply Finset.sum_congr rfl
  intro s _
  exact (ContinuousLinearMap.adjoint_inner_left T (v s) (u s)).symm

theorem tensorTargetLift_adjoint (T : E →L[ℂ] F) :
    (tensorTargetLift (ι := ι) (μ := μ) T).adjoint =
      tensorTargetLift (ι := ι) (μ := μ) T.adjoint := by
  apply ContinuousLinearMap.ext
  intro u
  apply ext_inner_right ℂ
  intro v
  rw [ContinuousLinearMap.adjoint_inner_left]
  simp only [MeasureTheory.L2.inner_def]
  apply integral_congr_ae
  filter_upwards [tensorTargetLift_apply_ae (ι := ι) T.adjoint u,
    tensorTargetLift_apply_ae (ι := ι) T v] with x hu hv
  rw [show tensorTargetLift (ι := ι) (μ := μ) T.adjoint u x =
      piLpMap (ι := ι) T.adjoint (u x) by ext s; exact hu s]
  rw [show tensorTargetLift (ι := ι) (μ := μ) T v x =
      piLpMap (ι := ι) T (v x) by ext s; exact hv s]
  rw [← piLpMap_adjoint]
  exact (ContinuousLinearMap.adjoint_inner_left
    (piLpMap (ι := ι) T) (v x) (u x)).symm

end Complete

section Factors

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

noncomputable abbrev FirstFactorSpace (ι α H : Type*) [Fintype ι] [MeasurableSpace α]
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] (μ : Measure α) : Type _ :=
  Lp (PiLp 2 (fun _ : ι => H)) 2 μ

noncomputable abbrev SecondFactorSpace (ι α H : Type*) [Fintype ι] [MeasurableSpace α]
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] (μ : Measure α) : Type _ :=
  Lp (PiLp 2 (fun _ : ι => FirstFactorSpace ι α H μ)) 2 μ

@[expose] noncomputable def firstFactorInsertion
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    FirstFactorSpace ι α H μ →L[ℂ] SecondFactorSpace ι α H μ :=
  tensorInsertion (H := FirstFactorSpace ι α H μ) f

@[expose] noncomputable def secondFactorInsertion
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    FirstFactorSpace ι α H μ →L[ℂ] SecondFactorSpace ι α H μ :=
  tensorTargetLift (ι := ι) (μ := μ) (tensorInsertion (H := H) f)

@[expose] noncomputable def doubleFactorInsertion
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    H →L[ℂ] SecondFactorSpace ι α H μ :=
  (firstFactorInsertion (H := H) f).comp (tensorInsertion (H := H) f)

omit [CompleteSpace H] in theorem secondFactorInsertion_comp_tensorInsertion
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    secondFactorInsertion (H := H) f ∘L tensorInsertion (H := H) f =
      doubleFactorInsertion (H := H) f := by
  exact tensorTargetLift_comp_tensorInsertion (ι := ι) (μ := μ)
    (E := H) (F := FirstFactorSpace ι α H μ) (tensorInsertion (H := H) f) f

@[expose] noncomputable def firstFactorProjection
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    SecondFactorSpace ι α H μ →L[ℂ] SecondFactorSpace ι α H μ :=
  (firstFactorInsertion (H := H) f).comp (firstFactorInsertion (H := H) f).adjoint

@[expose] noncomputable def secondFactorProjection
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    SecondFactorSpace ι α H μ →L[ℂ] SecondFactorSpace ι α H μ :=
  (secondFactorInsertion (H := H) f).comp (secondFactorInsertion (H := H) f).adjoint

theorem secondFactorInsertion_adjoint
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    (secondFactorInsertion (H := H) f).adjoint =
      tensorTargetLift (ι := ι) (μ := μ) (tensorInsertion (H := H) f).adjoint := by
  exact tensorTargetLift_adjoint (ι := ι) (μ := μ)
    (E := H) (F := FirstFactorSpace ι α H μ) (tensorInsertion (H := H) f)

theorem secondFactorInsertion_adjoint_comp_firstFactorInsertion
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    (secondFactorInsertion (H := H) f).adjoint ∘L firstFactorInsertion (H := H) f =
      tensorInsertion (H := H) f ∘L (tensorInsertion (H := H) f).adjoint := by
  rw [secondFactorInsertion_adjoint]
  exact tensorTargetLift_comp_tensorInsertion (tensorInsertion (H := H) f).adjoint f

theorem firstFactorInsertion_adjoint_comp_secondFactorInsertion
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    (firstFactorInsertion (H := H) f).adjoint ∘L secondFactorInsertion (H := H) f =
      tensorInsertion (H := H) f ∘L (tensorInsertion (H := H) f).adjoint := by
  have h := congrArg ContinuousLinearMap.adjoint
    (secondFactorInsertion_adjoint_comp_firstFactorInsertion (H := H) f)
  simpa only [ContinuousLinearMap.adjoint_comp, ContinuousLinearMap.adjoint_adjoint] using h

theorem operator_projection_product_first {H X Y : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [NormedAddCommGroup X] [InnerProductSpace ℂ X] [CompleteSpace X]
    [NormedAddCommGroup Y] [InnerProductSpace ℂ Y] [CompleteSpace Y]
    (A : X →L[ℂ] Y) (B : H →L[ℂ] X) (J : X →L[ℂ] Y)
    (hcross : A.adjoint ∘L J = B ∘L B.adjoint)
    (hcomm : J ∘L B = A ∘L B) :
    (A ∘L A.adjoint) ∘L (J ∘L J.adjoint) =
      (A ∘L B) ∘L (A ∘L B).adjoint := by
  have hadj := congrArg ContinuousLinearMap.adjoint hcomm
  simp only [ContinuousLinearMap.adjoint_comp] at hadj
  rw [ContinuousLinearMap.adjoint_comp]
  simp only [ContinuousLinearMap.comp_assoc]
  rw [← ContinuousLinearMap.comp_assoc A.adjoint J, hcross]
  simp only [ContinuousLinearMap.comp_assoc]
  apply ContinuousLinearMap.ext
  intro x
  exact congrArg (fun z => A (B z)) (congrArg (fun T => T x) hadj)

theorem firstFactorProjection_secondFactorProjection
    (f : Lp (EuclideanSpace ℂ ι) 2 μ) :
    firstFactorProjection (H := H) f ∘L secondFactorProjection (H := H) f =
      doubleFactorInsertion (H := H) f ∘L (doubleFactorInsertion (H := H) f).adjoint := by
  exact operator_projection_product_first _ _ _
    (firstFactorInsertion_adjoint_comp_secondFactorInsertion (H := H) f)
    (secondFactorInsertion_comp_tensorInsertion (H := H) f)

theorem operator_projection_comp_eq_of_comp_eq {H Y : Type*}
    [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
    [NormedAddCommGroup Y] [InnerProductSpace ℂ Y] [CompleteSpace Y]
    (D : H →L[ℂ] Y) (U : Y ≃ₗᵢ[ℂ] Y)
    (hU : U.toContinuousLinearEquiv.toContinuousLinearMap ∘L D = D) :
    (D ∘L D.adjoint) ∘L U.toContinuousLinearEquiv.toContinuousLinearMap =
      D ∘L D.adjoint := by
  have hleft : (U.symm : Y →L[ℂ] Y) ∘L D = D := by
    apply ContinuousLinearMap.ext
    intro x
    have hx := congrArg (fun T => T x) hU
    simp only [ContinuousLinearMap.comp_apply] at hx
    change U.symm (D x) = D x
    calc
      U.symm (D x) = U.symm (U (D x)) := congrArg U.symm hx.symm
      _ = D x := U.symm_apply_apply (D x)
  have hright := congrArg ContinuousLinearMap.adjoint hleft
  simp only [ContinuousLinearMap.adjoint_comp,
    LinearIsometryEquiv.adjoint_eq_symm] at hright
  have hright' : D.adjoint ∘L U.toContinuousLinearEquiv.toContinuousLinearMap =
      D.adjoint := by
    simpa only [LinearIsometryEquiv.symm_symm] using hright
  rw [ContinuousLinearMap.comp_assoc, hright']

end Factors

end LiebThirring
