/-
Copyright (c) 2026 Scott Armstrong, Amélie Loher. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Scott Armstrong, Amélie Loher
-/
module

public import LiebThirring.Kinetic.PauliLiftIntertwining
public import LiebThirring.Kinetic.PauliDoubleInsertion
public import LiebThirring.Kinetic.ContractionProjectionTransport

/-! # Identifying the actual coordinate projections with factor projections

The remaining-state unitaries intertwine insertion on `State` with insertion
on the two-factor carrier. Taking adjoints identifies the projections, and
their product is the operator generated by actual double insertion.
-/

public section

open MeasureTheory

namespace LiebThirring

/-- Pair currying identifies the first actual coordinate projection with the
first generic factor projection. -/
theorem pairCurrying_oneParticleProjection_left {N q : ℕ} (i j : Fin N)
    (hij : i ≠ j)
    (f : Lp (EuclideanSpace ℂ (Fin q)) 2 (volume : Measure Position))
    (ψ : State N q) :
    pairCurryingLinearIsometryEquiv (q := q) i j hij (oneParticleProjection i f ψ) =
      firstFactorProjection (H := PairRestState i j q) f
        (pairCurryingLinearIsometryEquiv (q := q) i j hij ψ) := by
  have h : (pairCurryingLinearIsometryEquiv (q := q) i j hij :
      State N q →L[ℂ] PairCurriedState i j q).comp (oneParticleInsertion i f) =
      (firstFactorInsertion (H := PairRestState i j q) f).comp
        (restCurryingLeftLinearIsometryEquiv (q := q) i j hij :
          RestState i q →L[ℂ] RestFactorState i j q) := by
    apply ContinuousLinearMap.ext
    intro v
    exact pairCurrying_oneParticleInsertion_left i j hij f v
  have ht := projection_transport_apply (pairCurryingLinearIsometryEquiv (q := q) i j hij)
    (restCurryingLeftLinearIsometryEquiv (q := q) i j hij) (oneParticleInsertion i f)
    (firstFactorInsertion (H := PairRestState i j q) f) h ψ
  rw [oneParticleInsertion_adjoint] at ht
  exact ht

/-- Pair currying identifies the second actual coordinate projection with the
second generic factor projection. -/
theorem pairCurrying_oneParticleProjection_right {N q : ℕ} (i j : Fin N)
    (hij : i ≠ j)
    (f : Lp (EuclideanSpace ℂ (Fin q)) 2 (volume : Measure Position))
    (ψ : State N q) :
    pairCurryingLinearIsometryEquiv (q := q) i j hij (oneParticleProjection j f ψ) =
      secondFactorProjection (H := PairRestState i j q) f
        (pairCurryingLinearIsometryEquiv (q := q) i j hij ψ) := by
  have h : (pairCurryingLinearIsometryEquiv (q := q) i j hij :
      State N q →L[ℂ] PairCurriedState i j q).comp (oneParticleInsertion j f) =
      (secondFactorInsertion (H := PairRestState i j q) f).comp
        (restCurryingRightLinearIsometryEquiv (q := q) i j hij :
          RestState j q →L[ℂ] RestFactorState i j q) := by
    apply ContinuousLinearMap.ext
    intro v
    exact pairCurrying_oneParticleInsertion_right i j hij f v
  have ht := projection_transport_apply (pairCurryingLinearIsometryEquiv (q := q) i j hij)
    (restCurryingRightLinearIsometryEquiv (q := q) i j hij) (oneParticleInsertion j f)
    (secondFactorInsertion (H := PairRestState i j q) f) h ψ
  rw [oneParticleInsertion_adjoint] at ht
  exact ht

/-- Pair currying also transports the operator generated by double insertion. -/
theorem pairCurrying_doubleParticleInsertion_projection {N q : ℕ} (i j : Fin N)
    (hij : i ≠ j)
    (f : Lp (EuclideanSpace ℂ (Fin q)) 2 (volume : Measure Position))
    (ψ : State N q) :
    pairCurryingLinearIsometryEquiv (q := q) i j hij
        (((doubleParticleInsertion i j hij f).comp
          (doubleParticleInsertion i j hij f).adjoint) ψ) =
      ((doubleFactorInsertion (H := PairRestState i j q) f).comp
        (doubleFactorInsertion (H := PairRestState i j q) f).adjoint)
          (pairCurryingLinearIsometryEquiv (q := q) i j hij ψ) := by
  exact projection_pullback_apply (pairCurryingLinearIsometryEquiv (q := q) i j hij)
    (doubleFactorInsertion (H := PairRestState i j q) f) ψ

/-- The product of two distinct coordinate projections is generated by actual
double insertion. No unit-vector hypothesis is needed for this identity. -/
theorem oneParticleProjection_comp_oneParticleProjection {N q : ℕ} (i j : Fin N)
    (hij : i ≠ j)
    (f : Lp (EuclideanSpace ℂ (Fin q)) 2 (volume : Measure Position)) :
    (oneParticleProjection i f).comp (oneParticleProjection j f) =
      (doubleParticleInsertion i j hij f).comp
        (doubleParticleInsertion i j hij f).adjoint := by
  apply ContinuousLinearMap.ext
  intro ψ
  apply (pairCurryingLinearIsometryEquiv (q := q) i j hij).injective
  change pairCurryingLinearIsometryEquiv (q := q) i j hij
    (oneParticleProjection i f (oneParticleProjection j f ψ)) = _
  rw [pairCurrying_oneParticleProjection_left, pairCurrying_oneParticleProjection_right,
    pairCurrying_doubleParticleInsertion_projection]
  exact congrArg (fun T : PairCurriedState i j q →L[ℂ] PairCurriedState i j q =>
    T (pairCurryingLinearIsometryEquiv (q := q) i j hij ψ))
      (firstFactorProjection_secondFactorProjection (H := PairRestState i j q) f)

end LiebThirring

end
